# Generated by Django 5.2.3 on 2025-06-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
