# Generated by Django 5.2.3 on 2025-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
