# Generated by Django 5.2.3 on 2025-07-03 14:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="front_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
