# Generated by Django 5.2.3 on 2025-06-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_address_useraddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraddress",
            old_name="user",
            new_name="customer",
        ),
    ]
