# Generated by Django 5.2.3 on 2025-06-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_user_useraddress_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="first_name",
            field=models.CharField(default="TEMP", max_length=20),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="last_name",
            field=models.CharField(default="TEMP", max_length=20),
        ),
    ]
