# Generated by Django 5.2.3 on 2025-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_useraddress_first_name_useraddress_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
    ]
