# Generated by Django 5.2.3 on 2025-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image_profile",
            field=models.ImageField(
                blank=True,
                default="uploads/image_profile/default.jpg",
                null=True,
                upload_to="uploads/image_profile",
            ),
        ),
    ]
