# Generated by Django 5.2.3 on 2025-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_image_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image_profile",
            field=models.ImageField(
                default="uploads/image_profile/default.pgn",
                null=True,
                upload_to="uploads/image_profile",
            ),
        ),
    ]
