# Generated by Django 5.2.3 on 2025-07-03 14:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_image_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image_profile",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
