# Generated by Django 5.2.3 on 2025-06-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipment_first_name",
            field=models.CharField(default="Unkown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipment_last_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
    ]
