# Generated by Django 5.2.3 on 2025-06-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_orderitem_product_name_alter_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
