# Generated by Django 5.2.3 on 2025-06-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("IN_TRANSIT", "IN TRANSIT"),
                    ("DELIVERED", "DELIVERED"),
                    ("LOST", "LOST"),
                ],
                default="PENDING",
            ),
        ),
    ]
