# Generated by Django 5.2.3 on 2025-06-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
    ]
