# Generated by Django 5.2.3 on 2025-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_orderitem_order_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="front_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/product"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
