# Generated by Django 5.2.3 on 2025-07-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_orderitem_front_image_orderitem_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="front_image",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_image_backup",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
