# Generated by Django 5.2.3 on 2025-07-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_remove_orderitem_front_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product_image_backup",
            new_name="product_image",
        ),
    ]
