# Generated by Django 5.2.3 on 2025-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_rename_product_image_backup_orderitem_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_image",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=100),
        ),
    ]
